spring.application.name=spring-ai-integration-openai

# OpenAI API configuration

spring.ai.openai.api-key=${OPENAI_API_KEY}
logging.level.org.springframework.ai.chat.client=DEBUG
logging.level.org.springframework.ai.openai=DEBUG
logging.level.org.springframework.web.client=DEBUG

# DB Configuration

spring.datasource.url=jdbc:mysql://localhost:3306/springai?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.ai.chat.memory.repository.jdbc.initialize-schema=always