spring.application.name=spring-ai-integration-openai

# OpenAI API configuration

spring.ai.openai.api-key=${OPENAI_API_KEY}
logging.level.org.springframework.ai.chat.client=DEBUG
logging.level.org.springframework.ai.openai=DEBUG
logging.level.org.springframework.web.client=DEBUG